directories:
  output: packages
  buildResources: resources
  app: builds\production
appId: com.electron.quizkonv
win:
  publish: null
mac:
  publish: null
  category: your.app.category.type
electronVersion: 11.0.4
